from src.model.duration.duration_base_model import DurationBaseModel
from src.model.duration.duration_chord_model import DurationChordModel
from src.model.duration.duration_full_model import DurationFullModel
