mlflow:
  experiment_name: duration - v2
  run_name: final model - compressed chords

dataset:
  encoding_type: duration
  polyphonic: False
  chord_encoding_type: compressed
  chord_extension_count: 12
  transpose_mode: all
#  sequence_size: 193
  sequence_size: 41

model:
  use_padding_idx: False
  start_pitch_symbol: 129
  end_pitch_symbol: 129
  start_attack_symbol: 2
  end_attack_symbol: 2
  start_duration_symbol: 0
  end_duration_symbol: 0

  offset_size: 48
  pitch_size: 130
  attack_size: 3
  metadata_size: 120

  embedding_size: 256
  lstm_num_layers: 3
  lstm_hidden_size: 512
  nn_hidden_size: 128
  nn_output_size: 32

  embedding_dropout_rate: 0
  nn_dropout_rate: 0
  lstm_dropout_rate: 0

  normalize: False
  gradient_clipping: 0.25

#  pitch_loss_weight: 0.8
  attack_loss_weight: 0.2

  pitch_loss_weight: 0.6
  duration_loss_weight: 0.4

training:
  num_batches: 20000
  batch_size: 128
  num_epochs: 30
  seed: 9876543
  learning_rate: 0.5
  momentum: 0.9
  weight_decay: 1e-6

