mlflow:
  experiment_name: mono_time_step_encoding
  run_name: default_run

dataset:
  encoding_type: duration
  polyphonic: False
  chord_encoding_type: extended
  chord_extension_count: 7
  duration_correction: 0
  transpose_mode: none
  sequence_size: 193

model:
  start_symbol: 129
  end_symbol: 130

  offset_size: 48
  pitch_size: 131
  attack_size: 1
  metadata_size: 0

  embedding_size: 256
  lstm_num_layers: 3
  lstm_hidden_size: 512
  nn_hidden_size: 128
  nn_output_size: 32

  embedding_dropout_rate: 0.5
  nn_dropout_rate: 0.5
  lstm_dropout_rate: 0.5

  normalize: False
  gradient_clipping: 0.25

  pitch_loss_weight: 0.5
  attack_loss_weight: 0.5

training:
  num_batches: 5000
  batch_size: 64
  num_epochs: 35
  seed: 1234567890
  learning_rate: 0.5
  momentum: 0.9
  weight_decay: 1e-6